### PR TITLE
UI Update

### PR DESCRIPTION
**Pull request by etmtvdp**
Hey John,

Here are the files for the UI update...

Had to spend some time in the java-classes for the UI to get it all to work....

Added a generic "utility" class (to help support re-formatting the dates, so when it's "today", the date shows "today" or "tomorrow", which (imho) is a lot nicer and easier to read for end-users...

I have previously built a XBMC control-GUI for GBPVR (a Windows based PVR solution), and I had that in there as well, makes things just a little easier...

I didn't spend much time on the "standard" listactivities, but more on the details-screens and the top-header for the programme-section. The "eye" icon (I included the svg-file I used to generate it), is actually a button that starts the player when clicked....

Have a look 'round... I pulled the "external player" support and will start playing with the fragmenst and actionbar, drop me a mail if you have questions / issues; I'll drop you a mail when I've played 'round with fragments etc. some more, and hopefully give you some screenshots for tablet UI...

### CODE REVIEW

**Comment by john-tornblom** [comment]
I seem to be getting java.lang.NullPointerException in the programme list.
Have you tested so that everything works?

2011/10/10 etmtvdp <
reply@reply.github.com>

**Comment by etmtvdp** [comment]
Hey John,

Haven't seen that myself. Any more info?

I'm running that version on my tablet... Oh, wait, maybe I left a reference
to the "external player"...

I'll look tomorrow.

//Ton
Op 16 okt. 2011 17:49 schreef "john-tornblom" <
reply@reply.github.com>
het volgende:

**Comment by etmtvdp** [comment]
Hey John,

Just checked, but I don't get that (and I see that I removed the
external-player stuff)....

Do you get this on the programme-list or on programme-details?

//Ton

**Comment by john-tornblom** [comment]
I got it in the programme-list, the channelName TextView was not found ;( . I will try to merge the UI again, perhaps I missed something.

**Pull request closed without merging**
