### PR TITLE
Little improvements

### PR DESCRIPTION
**Pull request by polini**
Hello John,

I made the following improvements:
- German language support
- Ability to deactivate the channel icons (Loading the icons made the application crash)
- Remove recording in menu of RecordingActivity
- Added search functionality
- Application logo changed

### CODE REVIEW

**Comment by john-tornblom** [comment]
Thanks! I've commited the new logo, german translation and the option for disabling the channel logo. You wouldn't happend to have a stack trace for the crash you encounter when downloading channel logos?

I''ve tested the search feature and it seems to work fine, great job. I'll commit togeather with some cosmetic fixes some other day when I have more time :)

**Comment by polini** [comment]
No, I haven't got a stack trace of the crash. I think, it was a Java heap size error, because there were too many threads. I'll try the new implementation...

Do you think, there's any chance to support live streaming to an Android phone? That would be a cool feature...

**Comment by john-tornblom** [comment]
OK, no problem. I've added a thread pool to fix that problem so hopefully you can enjoy the icons :)

The live streaming might be possible in a distant future. The problem is bandwidth and latency. I've done some small tests with reencoding the video stream at a slower bit rate as well as other codecs from within tvheadend and it could work. But for now I'll focus on making the app great at what it already does :)

**Comment by john-tornblom** [comment]
Search functionality has been added to master

**Pull request closed without merging**
